apiVersion: "cert-manager.io/v1alpha2"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt-staging"
spec:
  acme:
    email: "y.shapiro@agentvi.com"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: "letsencrypt-staging-issuer-account-key"
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: "kong"
